{"name": "test_a", "status": "skipped", "statusDetails": {"message": "XFAIL deliberate fail\n\nAssertionError: assert False", "trace": "@pytest.mark.dependency() #设置依赖关系\n    @pytest.mark.xfail(reason='deliberate fail')\n    def test_a():\n        sleep(5)\n>       assert False\nE       assert False\n\ntest_dependency.py:9: AssertionError"}, "start": 1631238566529, "stop": 1631238571530, "uuid": "ba0232a8-f6c7-4948-b5b1-977a7a096656", "historyId": "10618701e461573bbe81d2066362ad28", "testCaseId": "cb23bc25d0dd17b603b8d99a5b287bd8", "fullName": "test_dependency#test_a", "labels": [{"name": "tag", "value": "dependency"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='deliberate fail')"}, {"name": "suite", "value": "test_dependency"}, {"name": "host", "value": "DESKTOP-GRKQKVO"}, {"name": "thread", "value": "64652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dependency"}]}