{"name": "test_a", "status": "skipped", "statusDetails": {"message": "XFAIL deliberate fail\n\nAssertionError: assert False", "trace": "@pytest.mark.dependency() #设置依赖关系\n    @pytest.mark.xfail(reason='deliberate fail')\n    def test_a():\n>       assert False\nE       assert False\n\ntest_dependency.py:8: AssertionError"}, "start": 1631236577566, "stop": 1631236577566, "uuid": "ea706075-abf5-4b4e-9c96-218519ca1e70", "historyId": "10618701e461573bbe81d2066362ad28", "testCaseId": "cb23bc25d0dd17b603b8d99a5b287bd8", "fullName": "test_dependency#test_a", "labels": [{"name": "tag", "value": "dependency"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='deliberate fail')"}, {"name": "suite", "value": "test_dependency"}, {"name": "host", "value": "DESKTOP-GRKQKVO"}, {"name": "thread", "value": "62644-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dependency"}]}