{"name": "test_rerun", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n3 Failed Assumptions:\n\ntest_rerun.py:11: AssumptionFailure\n>>\tpytest.assume(1 == 2)\nAssertionError: assert False\n\ntest_rerun.py:13: AssumptionFailure\n>>\tpytest.assume(1 == 4)\nAssertionError: assert False\n\ntest_rerun.py:14: AssumptionFailure\n>>\tpytest.assume(1 == 5)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               3 Failed Assumptions:\nE               \nE               test_rerun.py:11: AssumptionFailure\nE               >>\tpytest.assume(1 == 2)\nE               AssertionError: assert False\nE               \nE               test_rerun.py:13: AssumptionFailure\nE               >>\tpytest.assume(1 == 4)\nE               AssertionError: assert False\nE               \nE               test_rerun.py:14: AssumptionFailure\nE               >>\tpytest.assume(1 == 5)\nE               AssertionError: assert False\n\n..\\venv\\lib\\site-packages\\six.py:718: FailedAssumption"}, "start": 1631242879455, "stop": 1631242879506, "uuid": "a488a304-8d57-461b-82a7-2a5b1a7d5a44", "historyId": "47c35f179f4b9f2c17e761a436dbbee0", "testCaseId": "558bc7562212911663d26c2ca57bd815", "fullName": "test_rerun#test_rerun", "labels": [{"name": "suite", "value": "test_rerun"}, {"name": "host", "value": "DESKTOP-GRKQKVO"}, {"name": "thread", "value": "63800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_rerun"}]}